### ISSUE TITLE
Error with Ti SDK 7+

### ISSUE THREAD

**Issue by SilvioLuis** [tdtsh/TiBubbleViewForAndroid#5]
I need to use this module in version 7.1 of sdk ... but it returns error

![captura de tela 2018-07-17 as 10 28 36](https://user-images.githubusercontent.com/6088371/42820307-335aa624-89ac-11e8-8456-9492ba7b7e94.png)

**Comment by m1ga** [comment]
As mentioned on Slack: https://github.com/tdtsh/TiBubbleViewForAndroid/pull/6
